### PR TITLE
Upstream merge 2024-09-20

### PR DESCRIPTION
**Pull request by leonardehrenfried**
This adds the ability to insert an extra leg when transferring at the exact same stop: https://github.com/opentripplanner/OpenTripPlanner/pull/5984

You need to enable the feature flag `ExtraTransferLegOnSameStop`.

It also fixes the parsing of safe_duration_offset but that is likely to change again: https://github.com/opentripplanner/OpenTripPlanner/pull/5984

The arrive by fix for Hopelink is not merge upstream yet, so please don't deploy this merge there. Use https://github.com/ibi-group/OpenTripPlanner/pull/223 instead.

### CODE REVIEW

**Comment by miles-grant-ibigroup** [comment]
For the new "transfer" leg am I right in seeing that it's generating a WALK type leg? Am I supposed to compare the from/to to identify that it's a transfer leg instead of a walking leg?

**Comment by leonardehrenfried** [comment]
All transfer legs are walk legs. For anything else we would need a new schema, which is a super breaking change.

**Comment by leonardehrenfried** [comment]
The distance is also 0.

**Review by miles-grant-ibigroup — APPROVED** [review]
Great thank you!

**Pull request merged**
