### PR TITLE
Use proper URLs for bike rental GBFS endpoints

### PR DESCRIPTION
**Pull request by evansiroky**
This update copy-pastes some code from the vehicle rental GBFS class so that the proper URLs are used in a particular GBFS feed.

### CODE REVIEW

**Comment by landonreed** [comment]
@evansiroky, did you have a link to a deployment in Data Tools dev that we could test with? Maybe now that we have a good way to deploy any commit of OTP, we should require a link to a deployment if the OTP PR would benefit from seeing the build in action.

**Comment by binh-dam-ibigroup** [comment]
This is for accommodating the GBFS per-language "folder" structure from BayWheels, correct?

**Comment by landonreed** [comment]
Yes, that's correct @binh-dam-ibigroup. I suppose you might as well give it a shot with our Bay Area deployment for testing. @evansiroky, did you upload the jar to our bucket? If so, what is it called?

**Comment by evansiroky** [comment]
This PR now also does the following:

- works for GBFS feeds where the root gbfs.json contents are not at `.../rootUrlPath/gbfs.json` but are instead at `.../rootUrlPath/`.
- Uploads a packaged jar file to the s3 bucket `otp-repo` after each travis build.

Relevant deployment with this update: https://fdot-otp.ibi-transit.com/

**Review by binh-dam-ibigroup — APPROVED** [review]

**Review by landonreed — APPROVED** [review]
LGTM. Only question is do we want to put the travis stuff in a separate branch so that it is easier to cherry-pick this PR into the main OpenTripPlanner repo (if this is code we intend to merge back)?

**Comment by evansiroky** [comment]
When I cherry-pick stuff I cherry-pick individual commits, so this is fine already since the travis stuff was isolated to a single commit.

**Pull request merged**
