### PR TITLE
Upstream merge 2022-03-22

### PR DESCRIPTION
**Pull request by leonardehrenfried**
This is an upstream merge that contains the following features relevant for IBI:

- **Java 17: Please make sure that the host uses this version**
- Performance improvements for P+R, B+R. Read how to enable it: http://docs.opentripplanner.org/en/dev-2.x/sandbox/VehicleToStopHeuristics/
- Vehicle positions. Configuration and GraphQL query: https://github.com/opentripplanner/OpenTripPlanner/pull/3981

Closes #97

### CODE REVIEW

**Review by miles-grant-ibigroup — APPROVED** [review]
It works great! Thanks so much. Having some issues with some RT feeds, but nothing showstopping for now.

**Comment by leonardehrenfried** [comment]
Ok, great. If you can point me towards a feed that works in OTP1 but not 2 I can upstream the IBI improvements.

**Comment by miles-grant-ibigroup** [comment]
It's a lot of the ATL feeds that are having some issues, although I know that some of them are currently undergoing review and adjustment because they are known to be incorrect/buggy. I'll double check everything and follow up with you offline

**Comment by leonardehrenfried** [comment]
Are these vehicle position or stop time feeds?

**Comment by miles-grant-ibigroup** [comment]
Vehicle position feeds

**Comment by leonardehrenfried** [comment]
Ok, I'd love to check them out if you have URLs.

**Comment by leonardehrenfried** [comment]
I tested with the Seattle ones.

**Comment by miles-grant-ibigroup** [comment]
Yeah those are working great for me too which makes me think it's a feed issue. Will keep you posted

**Pull request merged**
