### PR TITLE
Exclude MultiPolygons from single-geometry return.

### LINKED ISSUE #134: Errors processing scooter updates (OTP 1.x, TriMet)
## Expected behavior

OTP should be able to process scooter (rental vehicle) positions contained in a GBFS feed and plan trips that use scooters.

## Observed behavior

The processing errors with the message like below, and itinerary searches with scooter rentals do not return trips with scooters.

```
INFO (VehicleRentalUpdater.java:258) Applying vehicle rental region for: BIRD
ERROR (GraphUpdaterManager.java:144) Error while running graph writer org.opentripplanner.updater.vehicle_rental.VehicleRentalUpdater$VehicleRentalGraphWriterRunnable:
org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING (...) and LINESTRING (...) 
	at org.locationtech.jts.noding.FastNodingValidator.checkValid(FastNodingValidator.java:140) ~[jts-core-1.16.0.jar:na]
        ...
```

## Version of OTP used (exact commit hash or JAR name)

Current `ibi-dev` (1.x) branch.
Versions prior to https://github.com/ibi-group/OpenTripPlanner/commit/7744efc75ac45d82a082ad71eec51317e7e7ebd6 are not affected.

## Data sets in use (links to GTFS and OSM PBF files)

TriMet

## Command line used to start OTP

Normal parameters

## Router config and graph build config JSON

Any router config that ingests scooter GBFS updates.

## Steps to reproduce the problem

1. Build a graph using an above route-config.json
2. Run OTP using that graph
3. In this repo's own client UI, plan a trip requesting "Rental micromobility + transit" within locations that have them (e.g. Downtown Portland)
4. Observe that no scooter rentals are not included in the results. (With unaffected versions, scooter rentals are included.)

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Summary

This PR lets rental scooters be included when a user searches itineraries with rental micromobility+transit.

### Issue

Fix #134.

### Unit tests

Manually tested using Portland OR graph.

### Documentation

Added comment regarding MultiPolygons.

### CODE REVIEW

**Comment by demory** [comment]
@binh-dam-ibigroup can you please confirm that you are able to consistently plan rented-scooter trips at both ends of an itinerary? I have a local graph of this running and I can plan itineraries with scooters as the access mode but never the egress, even in areas where I know there is heavy coverage.

**Comment by binh-dam-ibigroup** [comment]
> @binh-dam-ibigroup can you please confirm that you are able to consistently plan rented-scooter trips at both ends of an itinerary? I have a local graph of this running and I can plan itineraries with scooters as the access mode but never the egress, even in areas where I know there is heavy coverage.

Good point on checking both ends of itineraries @demory. I am also not able to make OTP produce a plan with a scooter rental at the end, although when reversing origin and destination, a scooter rental at the beginning of the trip is available.

**Comment by binh-dam-ibigroup** [comment]
> > @binh-dam-ibigroup can you please confirm that you are able to consistently plan rented-scooter trips at both ends of an itinerary? I have a local graph of this running and I can plan itineraries with scooters as the access mode but never the egress, even in areas where I know there is heavy coverage.
> 
> Good point on checking both ends of itineraries @demory. I am also not able to make OTP produce a plan with a scooter rental at the end, although when reversing origin and destination, a scooter rental at the beginning of the trip is available.

@demory No change in code, but I here is an itinerary with a scooter rental both on departure and arrival.
Screen Shot 2022-10-17 at 3 13 22 PM

**Comment by demory** [comment]
After debugging this with @binh-dam-ibigroup we determined that the above unexpected behavior (MICROMOBILITY_RENT trips at the beginning but not the end of an itinerary) was caused by an invalid `regionsUrl` reference in my local `router-config.json`. Binh will look into whether we can better handle this case on the OTP side.

**Comment by binh-dam-ibigroup** [comment]
> After debugging this with @binh-dam-ibigroup we determined that the above unexpected behavior (MICROMOBILITY_RENT trips at the beginning but not the end of an itinerary) was caused by an invalid `regionsUrl` reference in my local `router-config.json`. Binh will look into whether we can better handle this case on the OTP side.

@demory I added dealing with local, not found `regionsUrl` cases in https://github.com/ibi-group/OpenTripPlanner/pull/135/commits/3ae7ad3133bf1b519d30a803269a2fe2149e8e7a and https://github.com/ibi-group/OpenTripPlanner/pull/135/commits/7c06e4b45dd67fa43176a9aac8ebed5bf6580fe8, so that misconfiguring a local `regionsUrl` file in a vehicle rental updater does not interfere with planning scooter rental itineraries. cc @leonardehrenfried.

**Review by demory — APPROVED** [review]

**Review by leonardehrenfried — APPROVED** [review]
Since it wouldn't be very hard to do I would prefer there to be a unit test for GeoJsonUtil but given that it's code that will be replaced soon-ish I'm happy to give my approval.

**Pull request merged**
