### PR TITLE
Upstream merge 2022-04-22

### PR DESCRIPTION
**Pull request by leonardehrenfried**
This is a larger PR which contains an autoformatting of all Java files in the repo.

The changes relevant for IBI:

- Less confusing GTFS-RT logs: https://github.com/opentripplanner/OpenTripPlanner/pull/4094
- Handle GTFS-RT vehicle positions without a service day: https://github.com/opentripplanner/OpenTripPlanner/pull/4066
- GBFS form factor in GraphQL API: https://github.com/opentripplanner/OpenTripPlanner/pull/4062
- Bugfix in REST API trip times: https://github.com/opentripplanner/OpenTripPlanner/pull/4056 (not sure if this one is really new or was in the previous merge)
- Accessibility score (for transit): https://github.com/opentripplanner/OpenTripPlanner/pull/4045 
  Doc is at http://docs.opentripplanner.org/en/dev-2.x/Accessibility/ (Check the link to the complete config examples at the bottom of the page)

### CODE REVIEW

**Comment by miles-grant-ibigroup** [comment]
@leonardehrenfried I'm guessing the smoke tests are failing because of outdated GTFS?

**Comment by leonardehrenfried** [comment]
Yes, the [Cobblinc Flex feed](https://internal-test-gtfs-testing.s3.amazonaws.com/cobblinc-gtfs-flex.zip) will expire on Sunday and since it always does the search on the next Monday the test fails.

Do you know if there is a URL for the feed that is continuously updated? Perhaps @philip-cline knows?

**Comment by miles-grant-ibigroup** [comment]
It might be a good idea to make a special version of that flex feed with calendars extended years in advance? Especially since we made that flex feed. What do you think @philip-cline

**Comment by philip-cline** [comment]
I think that makes sense. I'll push a new feed to that URL that has calendars super-extended.

**Comment by leonardehrenfried** [comment]
That would be great. Once that is done, can you restart the smoke test here?

**Comment by leonardehrenfried** [comment]
@philip-cline I just tried the smoke tests with the newest version of the Cobblinc Flex file. The test fails because locations.geojson is incorrect and puts the flex zones onto Antarctica: https://gist.github.com/leonardehrenfried/6ed72398f96ec16944dc7db903c35423 :)

I looks like lat/long are swapped. (In GeoJson its `[long, lat]` not the other way round...)

**Comment by philip-cline** [comment]
Ugh looks like there's an issue with the DT location.geojson export. I'll edit manually and reupload

**Comment by philip-cline** [comment]
Ok, I've reuploaded the file to that link, but AWS may cache the old file so lmk if you can get the latest. Otherwise here's another download link that should work: https://drive.google.com/uc?export=download&id=1arN7O4xfYRlm0ZOp19yj8XFqXdfYl4XI

**Comment by leonardehrenfried** [comment]
The download now has lat/long in the correct order.

I'm starting the smoke test.

**Comment by leonardehrenfried** [comment]
Smoke tests are green now! Thanks for the quick help.

**Pull request merged**
