### PR TITLE
Upstream merge 2022-10-13

### PR DESCRIPTION
**Pull request by leonardehrenfried**
### Relevant to IBI:

- This adds the new fare service for correctly combining interlined legs: https://github.com/opentripplanner/OpenTripPlanner/pull/4509 To use it for Septa use `"fares": "combine-interlined-legs"`.
- Improve the exclusion of pedestrian tunnels in Houston: https://github.com/opentripplanner/OpenTripPlanner/pull/4505
- Remove unnecessary GTFS-RT `sourceType`: https://github.com/opentripplanner/OpenTripPlanner/pull/4525

### Config change

~~There is another small config change for vehicle positions. Instead of `sourceType=gtfs-http` it is now `sourceType=gtfs-rt-http`.~~

~~There are examples for both changes in the following commit: https://github.com/ibi-group/OpenTripPlanner/commit/8590e21603133408c7e3adeee7e9de3b19e1280b~~

EDIT: I forgot that there is another one. The spelling of the config value has changed: https://github.com/ibi-group/OpenTripPlanner/commit/6e36ec93433d93145eca04dd7085c76cc5fce62e 
That change is backwards-compatible though.

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
One more relevant feature was merged upstream so I included it here: the separate vector tile layers for rental stations and free-floating vehicles.

Check the documentation at: http://docs.opentripplanner.org/en/dev-2.x/sandbox/MapboxVectorTilesApi/

**Comment by miles-grant-ibigroup** [comment]
Looks like `flex` isn't a valid key anymore! How do we adjust the maxTransferDurationSeconds?

**Comment by leonardehrenfried** [comment]
I think you put that in otp-config.json isn't it? It should be in router-config.json.

**Comment by miles-grant-ibigroup** [comment]
Did it get moved?

**Comment by leonardehrenfried** [comment]
No, it was always like that. Example: https://github.com/opentripplanner/OpenTripPlanner/blob/bfd9726202d9b1ee6e459f8569a5f1b433083adb/src/test/resources/standalone/config/router-config.json#L74

The default is 240 so it didn't matter.

**Comment by miles-grant-ibigroup** [comment]
Ah so all our configs have always been wrong haha

Thanks for looking into it! Will merge once all the sourceTypes are updated

**Comment by leonardehrenfried** [comment]
@miles-grant-ibigroup There have been a few more changes merged upstream so I updated the original description. The big change is that `sourceType` is no longer necessary for GTFS-RT trip/vehicle position updaters, so you don't need to change any config files.

**Comment by leonardehrenfried** [comment]
An example configuration is here: https://github.com/ibi-group/OpenTripPlanner/blob/upstream-merge-2022-10-13/smoke-tests/septa/router-config.json

**Comment by miles-grant-ibigroup** [comment]
Will an invalided `sourceType` be accepted as well? As in is the field totally deprecated?

**Comment by leonardehrenfried** [comment]
You can write any string you want in there. It's completely ignored. OTP will print a warning that a config param is unknown though but that's it.

**Comment by miles-grant-ibigroup** [comment]
Amazing thanks for letting me know! This is then ready for merge.

**Review by miles-grant-ibigroup — APPROVED** [review]

**Pull request merged**
