### PR TITLE
Upstream merge 2023-07-10

### PR DESCRIPTION
**Pull request by leonardehrenfried**
This merge doesn't contain anything immediately relevant for IBI but there are a number of larger refactorings that I want to run through the smoke test pipeline to check if everything still works.

### CODE REVIEW

**Review by miles-grant-ibigroup — CHANGES_REQUESTED** [review]
Is `vehicle-positions` no longer a valid updater type??

**Comment by leonardehrenfried** [comment]
There is a smoke test for Denver and Seattle which checks the vehicle positions and they can be successfully fetched. Why do you think it's no longer valid?

**Comment by miles-grant-ibigroup** [comment]
Seeing this:

`14:39:09.621 ERROR (OTPMain.java:55) The updater config type is unknown: vehicle-positions`

**Comment by leonardehrenfried** [comment]
What is the router-config in question?

The following works for the smoke test: https://github.com/opentripplanner/OpenTripPlanner/blob/efb34f22dd0d2b955dc2c9c0f2b5ad1926cee101/smoke-tests/denver/router-config.json#L1-L0

**Comment by leonardehrenfried** [comment]
Is it possible that you've deployed a very old version? I cannot find the error string in the current version and OTPMain.java:55 is not a line that logs anything.

**Review by miles-grant-ibigroup — APPROVED** [review]
Silly me. Working great

**Pull request merged**
