### PR TITLE
Upstream merge 2023-10-20

### PR DESCRIPTION
**Pull request by leonardehrenfried**
This release brings in the geocoder improvements from https://github.com/opentripplanner/OpenTripPlanner/pull/5401. It also removes the indexing of street corners in the geocoder so start up time is improved.

Another nice new feature is the support for realtime vehicle occupancy from GTFS-RT feeds.

#### Edit

The PR that fixes the CCSWW feed was also merge a few minutes ago: https://github.com/opentripplanner/OpenTripPlanner/pull/5376

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
There is a critical bug in upstream so let's wait until I've clarified how bad it is.

**Comment by leonardehrenfried** [comment]
The bug only appears in a pretty rare edge case (two stops times using the same minute but different number of seconds) and its consequences are benign: the transfer optimization selects the wrong one of these stops.

It's only because another change (not yet merged) surfaced that it even existed.

**Comment by miles-grant-ibigroup** [comment]
Draft/BLocked until this <1 minute bug is fixed

**Review by miles-grant-ibigroup — APPROVED** [review]
Things are working well let's merge

**Pull request merged**
