### PR TITLE
Upstream merge 2022-11-24

### PR DESCRIPTION
**Pull request by leonardehrenfried**
This is just another housekeeping merge in order to not let the diff grow too much.

The only thing that might be vaguely interesting to IBI is the via search, also known as intermediate places.

### CODE REVIEW

**Comment by miles-grant-ibigroup** [comment]
How does the via search work? The otp1 way of doing it (`intermediatePlaces`) doesn't seem to be working

**Comment by leonardehrenfried** [comment]
Ah, I just realised that it's not hooked up to any API yet!

Here is a PR that adds it to the Transmodel (Entur) API: https://github.com/opentripplanner/OpenTripPlanner/pull/4607

**Comment by miles-grant-ibigroup** [comment]
Ah good to know thanks! Will keep an eye out

**Review by miles-grant-ibigroup — APPROVED** [review]
exciting

**Pull request merged**
