### PR TITLE
Upstream merge 2023-08-15

### PR DESCRIPTION
**Pull request by leonardehrenfried**
This merge adds the missing property `leg.headsign` (as opposed to `trip.tripHeadsign`) to the GraphQL API: https://github.com/opentripplanner/OpenTripPlanner/pull/5290

If you're interested how a `leg.headsign` is resolved when both are set, someone documented the expected behaviour here: https://github.com/opentripplanner/OpenTripPlanner/pull/5205

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
cc @binh-dam-ibigroup

**Comment by binh-dam-ibigroup** [comment]
> If you're interested how a `leg.headsign` is resolved when both are set, someone documented the expected behaviour here: [opentripplanner#5205](https://github.com/opentripplanner/OpenTripPlanner/pull/5205)

@leonardehrenfried This means the UI should only be using `leg.headsign`, correct?

**Comment by leonardehrenfried** [comment]
@binh-dam-ibigroup Yes, indeed. It's the correct thing to display in a routing result. In a trip viewer you might have more specific requirements.

**Review by miles-grant-ibigroup — APPROVED** [review]
Tested working

**Pull request merged**
