### PR TITLE
fix: don’t apply routeType alerts to all routes of that type

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
To be completed by pull request submitter:

- [ ] **issue**: Link to or create an [issue](https://github.com/opentripplanner/OpenTripPlanner/issues) that describes the relevant feature or bug. Add [GitHub keywords](https://help.github.com/articles/closing-issues-using-keywords/) to this PR's description (e.g., `closes #45`).
- [ ] **roadmap**: Check the [roadmap](https://github.com/orgs/opentripplanner/projects/1) for this feature or bug. If it is not already on the roadmap, PLC will discuss as part of the review process.
- [ ] **tests**: Have you added relevant test coverage? Are all the tests passing on [the continuous integration service (Travis CI)](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Developers-Guide.md#continuous-integration)?
- [ ] **formatting**: Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Developers-Guide.md#code-style)? 
- [ ] **documentation**: If you are adding a new configuration option, have you added an explanation to the [configuration documentation](docs/Configuration.md) tables and sections?
- [ ] **changelog**: add a bullet point to the [changelog file](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Changelog.md) with description and link to the linked issue

To be completed by @opentripplanner/plc:

- [ ] reviews and approvals by 2 members, ideally from different organizations
- [ ] **after merging**: update the relevant card on the [roadmap](https://github.com/orgs/opentripplanner/projects/1)

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Do you need this urgently or is it ok for me to double-check the spec carefully on Monday and figure out the correct behaviour?

**Comment by miles-grant-ibigroup** [comment]
No hurry at all!

**Comment by miles-grant-ibigroup** [comment]
I was just pruning some old issues and came across this again -- I think we can probably close this unless you've found any new info about the proper way this should be done?

**Comment by leonardehrenfried** [comment]
Sorry, that completely slipped my mind.

OTP2 implements the behaviour that's in this PR so I lean towards thinking that it's correct. I approve.

**Review by leonardehrenfried — APPROVED** [review]

**Comment by miles-grant-ibigroup** [comment]
No stress -- thanks for looking into it!

**Review by br648 — APPROVED** [review]
From a code POV, all is good with me.

**Pull request merged**
