### PR TITLE
Upstream merge 2023-04-11

### PR DESCRIPTION
**Pull request by leonardehrenfried**
This is a small merge which contains a single bugfix reported by @daniel-heppner-ibigroup: https://github.com/opentripplanner/OpenTripPlanner/pull/5028

### Edit I

One new thing in this merge is OTP's ability to switch to JSON logs. This is useful once IBI wants to start using an aggregated log service like Loki, Datadog, Logz.io.

https://docs.opentripplanner.org/en/dev-2.x/Logging/

### Edit II

Uber support has just been merged upstream: https://github.com/opentripplanner/OpenTripPlanner/pull/4979

Docs: https://docs.opentripplanner.org/en/dev-2.x/sandbox/RideHailing/

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Hey @miles-grant-ibigroup, have you seen this PR?

**Comment by miles-grant-ibigroup** [comment]
Hoping to get to this today or tomorrow. Do you think it's worth updating the merge branch?

**Comment by leonardehrenfried** [comment]
With all the lasted updates since last week? I can definitely do that. It's good to not let the changes pile up too much.

**Comment by leonardehrenfried** [comment]
It's that time of the year again: MARTA is changing their schedules and are seemingly unable to publish their new feed more than 2 days ahead of time. Need to change a few dates.

**Review by miles-grant-ibigroup — APPROVED** [review]
All working thanks for the merge

**Pull request merged**
