### PR TITLE
Upstream merge 2022-03-29

### PR DESCRIPTION
**Pull request by leonardehrenfried**
This fixes the HTTP timeout so that the cobblinc bus positions feed no longer blocks the rest of the realtime updaters.

### CODE REVIEW

**Review by miles-grant-ibigroup — APPROVED** [review]
Still having some trouble getting the ATL feeds to match to the gtfs, but this still works great with other feeds!

**Comment by leonardehrenfried** [comment]
Having some warnings/errors is normal but if you have specific fixes in the IBI fork that should go upstream I'd love to see them.

**Comment by miles-grant-ibigroup** [comment]
Yeah there's a lot of failure. That realtime dashboard you were talking about might be helpful... We'll see if others are interested in it too

**Comment by leonardehrenfried** [comment]
I'll discuss with @demory tomorrow to see if we should be making a task out of this.

**Pull request merged**
