### PR TITLE
Upstream merge 2023-06-29

### PR DESCRIPTION
**Pull request by leonardehrenfried**
The only relevant change for IBI is the NPE fix in the vehicle position updater that @amy-corson-ibigroup reported: https://github.com/opentripplanner/OpenTripPlanner/pull/5212

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
@miles-grant-ibigroup The smoke tests are failing because the vehicle positions in Denver don't have a trip ID. :shrug: Is this a known problem?

I will try again later, maybe it will fix itself.

**Comment by miles-grant-ibigroup** [comment]
Never heard of this happening, let's hope it's a time-dependent thing!

**Comment by leonardehrenfried** [comment]
It fixed itself. :man_shrugging:

**Review by miles-grant-ibigroup — CHANGES_REQUESTED** [review]
Could you possibly revert that last commit? Otherwise all working well

**Comment by leonardehrenfried** [comment]
Already done.

**Review by miles-grant-ibigroup — APPROVED** [review]
Working

**Pull request merged**
