### PR TITLE
refactor(Message.properties): more easily allow user to recover from PATH_NOT_FOUND

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
To be completed by pull request submitter:

- [ ] **issue**: Link to or create an [issue](https://github.com/opentripplanner/OpenTripPlanner/issues) that describes the relevant feature or bug. Add [GitHub keywords](https://help.github.com/articles/closing-issues-using-keywords/) to this PR's description (e.g., `closes #45`).
- [ ] **roadmap**: Check the [roadmap](https://github.com/orgs/opentripplanner/projects/1) for this feature or bug. If it is not already on the roadmap, PLC will discuss as part of the review process.
- [ ] **tests**: Have you added relevant test coverage? Are all the tests passing on [the continuous integration service (Travis CI)](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Developers-Guide.md#continuous-integration)?
- [ ] **formatting**: Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Developers-Guide.md#code-style)? 
- [ ] **documentation**: If you are adding a new configuration option, have you added an explanation to the [configuration documentation](docs/Configuration.md) tables and sections?
- [ ] **changelog**: add a bullet point to the [changelog file](https://github.com/opentripplanner/OpenTripPlanner/blob/master/docs/Changelog.md) with description and link to the linked issue

To be completed by @opentripplanner/plc:

- [ ] reviews and approvals by 2 members, ideally from different organizations
- [ ] **after merging**: update the relevant card on the [roadmap](https://github.com/orgs/opentripplanner/projects/1)

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
This is a very annoying problem.

7GB should be plenty of RAM.

I will be looking into this some more tomorrow.

**Comment by leonardehrenfried** [comment]
I managed to make the tests pass on CI and explained a bit more here: https://github.com/ibi-group/OpenTripPlanner/pull/87#issuecomment-1018362414

**Comment by miles-grant-ibigroup** [comment]
Thank you for finding that fix Leonard! I really wonder what caused the issue...

**Comment by miles-grant-ibigroup** [comment]
@leonardehrenfried the actual changes from this PR have turned out not to be needed. Are the ci changes part of #87/can this PR be safely closed?

**Comment by leonardehrenfried** [comment]
Yes, Daniel cherry picked it into his branch.

**Comment by miles-grant-ibigroup** [comment]
Thanks so much for clarifying!

**Pull request closed without merging**
