### PR TITLE
Upstream merge 2022-09-12

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
Adds ATL fare updates

### CODE REVIEW

**Comment by miles-grant-ibigroup** [comment]
Assigning to @leonardehrenfried to figure out why the ci is failing

**Comment by leonardehrenfried** [comment]
I took over this PR fixed the problem of the smoke test not compiling: the issue was that the merge of this branch plus IBI's branch went ok but the type `Fare` has been moved and renamed. If you rebase onto IBI's fork first you can see the problem locally and that is easily fixed.

Now the smoke tests actually do their job and fail because there is an problem with the API mapper when the Houston fare code is combined with the Fares V2 code.

I will resolve this upstream. 

@miles-grant-ibigroup How urgent is this. Do you want a pfusch branch?

**Comment by miles-grant-ibigroup** [comment]
Thanks for looking into it @leonardehrenfried! No hurry on this. I'll close this for now and we can re-open once everything is fixed!

**Comment by leonardehrenfried** [comment]
I just noticed that this was because of the ATL fare module. This is actually not upstream yet. Did you mean the ATL walking config with the trunk roads?

**Comment by miles-grant-ibigroup** [comment]
Yes I did thanks for catching that! Either way both can wait until the next main upstream merge PR!

**Pull request closed without merging**
